=== stringbean/sbt-dependency-lock/src/main/paradox/lockfile-v1.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://stringbean.github.io/sbt-dependency-lock/lockfile-v1.schema.json",
  "title": "sbt-dependency-lock lockfile v1",
  "description": "Lockfile for sbt-dependency-lock - version 1 format",
  "type": "object",
  "required": [
    "lockVersion",
    "timestamp",
    "configurations",
    "dependencies"
  ],
  "properties": {
    "lockVersion": {
      "type": "integer",
      "description": "Version of the lockfile"
    },
    "timestamp": {
      "type": "string",
      "format": "date-time",
      "description": "File generation timestamp"
    },
    "configurations": {
      "type": "array",
      "description": "List of sbt build configurations in the current project",
      "items": {
        "type": "string"
      }
    },
    "dependencies": {
      "type": "array",
      "description": "List of all the dependencies in the current project",
      "items": {
        "required": [
          "org",
          "name",
          "version",
          "artifacts"
        ],
        "properties": {
          "org": {
            "type": "string",
            "description": "Organisation of the resolved dependency from Ivy/Maven"
          },
          "name": {
            "type": "string",
            "description": "Name of the resolved dependency from Ivy/Maven"
          },
          "version": {
            "type": "string",
            "description": "Version of the resolved dependency"
          },
          "artifacts": {
            "type": "array",
            "description": "List of all the artifacts for the dependency",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "description": "Filename of the artifact",
                  "examples": [
                    "commons-lang3.jar"
                  ]
                },
                "hash": {
                  "type": "string",
                  "description": "Checksum of the artifact prefixed with the checksum algorithm",
                  "examples": [
                    "sha1:0122c7cee69b53ed4a7681c03d4ee4c0e2765da5"
                  ]
                }
              }
            }
          },
          "configurations": {
            "type": "array",
            "description": "List of the sbt configurations that include this dependency",
            "items": {
              "type": "string",
              "examples": [
                [
                  "compile",
                  "test"
                ]
              ]
            }
          }
        }
      }
    }
  }
}

=== stringbean/sbt-dependency-lock/src/test/resources/lockfile/v1/with-dependencies.json
{
  "lockVersion": 1,
  "timestamp": "2021-05-11T12:00:00.000Z",
  "configurations": [
    "compile",
    "test"
  ],
  "dependencies": [
    {
      "org": "org.scala-lang",
      "name": "scala-library",
      "version": "2.12.10",
      "artifacts": [
        {
          "name": "scala-library.jar",
          "hash": "sha1:3509860bc2e5b3da001ed45aca94ffbe5694dbda"
        }
      ],
      "configurations": [
        "compile",
        "test"
      ]
    },
    {
      "org": "org.scala-lang",
      "name": "scala-reflect",
      "version": "2.12.10",
      "artifacts": [
        {
          "name": "scala-reflect.jar",
          "hash": "sha1:14cb7beb516cd8e07716133668c427792122c926"
        }
      ],
      "configurations": [
        "test"
      ]
    }
  ]
}
